[CR254] Set "image_version" to "default" in all sample config files
hashicorp/packer-plugin-azure pull request #255
Opened 2022-12-20 04:43 UTC by nkadel

Feature request 254 requests adding the "image_version" set to the default "latest" value consistently in every sample file. Some have it, some don't, let's be consistent if we can.

2022-12-20 04:44 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/packer-plugin-azure?pullRequest=255)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/packer-plugin-azure?pullRequest=255)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/packer-plugin-azure?pullRequest=255).</sub>

2023-02-02 15:45 UTC, JenGoldstrich requested changes
Hey @nkadel, thanks for making this contribution.

I think it would be better if this change only applied to the templates in the example directory and the docs/builders directory, the other templates you've changed are not meant to be examples, and are instead used as part of automated testing, and it makes the change a bit more disruptive, can we only apply it to templates we don't use in automated testing?

2023-04-24 17:28 UTC, JenGoldstrich commented
Closing due to inactivity, but we should update these examples soon as they are very out of date I agree, I would just prefer to focus on adding new examples that use HCL, and plugin features added recently.

2023-04-24 17:28 UTC, closed without merging

2023-04-25 00:48 UTC, nkadel commented
I don't see why these can't be set explicitly everywhere, to allow the pipelines access to override them as desired. Putting in the "version" of "latest" simply makes clear that there is, indeed, an additional variable and its default value.